rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"

eureka-server:
  image:  trproject-test/eureka-server
  hostname: eureka-server
  ports:
    - "8761:8761"

user-service:
  image:  trproject-test/user-service
  links:
    - "eureka-server"
    - "rabbitmq"

zuul:
  image:  trproject-test/zuul
  ports:
    - "8060:8060"
  links:
    - "eureka-server"
    - "user-service"
    - "rabbitmq"