eureka-server:
  image:  trproject-test/eureka-server
  hostname: eureka-server
  ports:
    - "8761:8761"

user-service:
  image:  trproject-test/user-service
  links:
    - "eureka-server"

zuul:
  image:  trproject-test/zuul
  ports:
    - "8060:8060"
  links:
    - "eureka-server"
    - "user-service"